[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 1
fs_permissions = [{ access = "read", path = "./test/data" }, { access = "read", path = "./out" }]

eth_rpc_url = "https://eth.drpc.org"

[profile.default.optimizer_details]
yul = true
yulDetails = { stackAllocation = true, optimizerSteps = "dhfoDgvulfnTUtnIf" }

[rpc_endpoints]
mainnet = "https://eth.drpc.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options